improve app layout
profcomff/aggregator-app pull request #34
Opened 2023-02-03 22:29 UTC by physphile

2023-02-03 22:44 UTC, grigoriev-semyon approved these changes

2023-02-03 22:47 UTC, dyakovri requested changes

2023-02-03 22:47 UTC, dyakovri commented on src/microfrontend-layout.html
> +    </main>
Тут не хватает devtools и default я сюда переносил

2023-02-04 09:27 UTC, dyakovri approved these changes

2023-02-04 17:21 UTC, merged